import os
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet

REPORTS_DIR = "./data/reports"


def generate_hmis_pdf(worker_name: str, month: int, year: int, rows: list[dict]) -> str:
    os.makedirs(REPORTS_DIR, exist_ok=True)
    filename = f"HMIS_{worker_name.replace(' ', '_')}_{year}_{month:02d}.pdf"
    path = os.path.join(REPORTS_DIR, filename)

    doc = SimpleDocTemplate(path, pagesize=A4, topMargin=1.5 * cm, bottomMargin=1.5 * cm)
    styles = getSampleStyleSheet()
    story = [
        Paragraph("HMIS Monthly Report (Auto-Generated by SevakAI)", styles["Title"]),
        Paragraph(f"Worker: {worker_name} &nbsp;&nbsp; Month: {month}/{year}", styles["Normal"]),
        Paragraph(f"Generated: {datetime.now().isoformat(timespec='seconds')}", styles["Normal"]),
        Spacer(1, 16),
    ]

    if rows:
        headers = ["Patient", "Category", "ANC", "High-Risk", "IFA Non-Compliant", "BP Recorded", "Referral"]
        table_data = [headers]
        for r in rows:
            table_data.append([
                r.get("patient_name", ""),
                r.get("reporting_category", ""),
                "Y" if r.get("anc_visit_recorded") else "-",
                "Y" if r.get("high_risk_pregnancy_flagged") else "-",
                "Y" if r.get("ifa_non_compliance_flagged") else "-",
                "Y" if r.get("bp_recorded") else "-",
                "Y" if r.get("referral_generated") else "-",
            ])
        table = Table(table_data, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E2761")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F2F2F2")]),
        ]))
        story.append(table)
    else:
        story.append(Paragraph("No visits recorded for this period.", styles["Normal"]))

    doc.build(story)
    return path
